name: Linux Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  Build-Linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      
      - name: Install dependencies
        run: |
          sudo apt install libdrm-dev libfontconfig1-dev nasm
          sudo pip3 install meson

      - name: Compile and install libva
        run: |
          git clone --depth 1 --branch v2.23-branch https://github.com/intel/libva.git
          cd libva
          mkdir build 
          cd build 
          meson .. -Dprefix=/usr -Dlibdir=/usr/lib/x86_64-linux-gnu
          ninja
          sudo ninja install
          
      - name: Download mpv source code
        run: git clone --depth 1 --branch release/0.41 https://github.com/mpv-player/mpv.git
        
      - name: Initialize subprojects
        run: |
          cd mpv
          
          meson wrap update-db
          
          meson wrap install expat
          
          mkdir -p subprojects

          cat <<EOF > subprojects/libplacebo.wrap
          [wrap-git]
          url = https://github.com/haasn/libplacebo
          revision = master
          depth = 1
          clone-recursive = true
          EOF
          
          cat <<EOF > subprojects/libass.wrap
          [wrap-git]
          revision = master
          url = https://github.com/libass/libass
          depth = 1
          EOF
          
          cat <<EOF > subprojects/ffmpeg.wrap
          [wrap-git]
          url = https://github.com/koolla73/ffmpeg-meson.git
          revision = meson-8.1-custom
          depth = 1
          [provide]
          libavcodec = libavcodec_dep
          libavdevice = libavdevice_dep
          libavfilter = libavfilter_dep
          libavformat = libavformat_dep
          libavutil = libavutil_dep
          libswresample = libswresample_dep
          libswscale = libswscale_dep
          EOF

      - name: Copy libmpv include headers
        run: |
          mkdir -p upload/bin
          mkdir -p upload/include/mpv
          mkdir -p upload/lib
          cp -r mpv/include/mpv/. upload/include/mpv
          
      - name: Configure mpv
        run: |
          cd mpv
          meson setup -Ddefault_library=static -Dprefer_static=true \
          -Dc_link_args='-static' -Dcpp_link_args='-static' \
          -Dffmpeg:default_library=static -Dlibass:default_library=static \
          -Dbzip2:default_library=static -Dfreetype2:default_library=static \
          -Dfribidi:default_library=static -Dglib:default_library=static -Dgoogle-brotli:default_library=static \
          -Dgraphite2:default_library=static -Dharfbuzz:default_library=static -Dlibpng:default_library=static \
          -Dopenssl:default_library=static -Dpcre2:default_library=static -Dwin-iconv:default_library=static \
          -Dzlib:default_library=static \
          -Dffmpeg:gpl=enabled -Dffmpeg:openssl=enabled -Dffmpeg:libxml2=enabled build

      - name: Compile mpv
        run: |
          cd mpv
          meson compile -C build
          
      - name: Install mpv
        run: |
          cd mpv
          sudo meson install -C build
          
      - name: List all files
        run: sudo ls -R / > output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: mpv-Linux-Files
          path: ${{github.workspace}}/output.txt
          if-no-files-found: error
          retention-days: 1
